# Framework Configuration
framework:
    translator:     ~
    form:           ~
    mailer:         ~
    assets:         ~
    secret:         false
    test:           ~
    session:
        storage_id: session.storage.mock_file
    profiler: { only_exceptions: false }