# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    firewalls:

        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        admin:
            lazy:                     true
            pattern:                  /admin(.*)
            provider:                 sonata_user_bundle
            context:                  user
            form_login:
                login_path:           sonata_user_admin_security_login
                check_path:           sonata_user_admin_security_check
                default_target_path:  sonata_admin_dashboard
            logout:
                path:       sonata_user_admin_security_logout
                target:     sonata_user_admin_security_login

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    password_hashers:
        Sonata\UserBundle\Model\UserInterface: auto

    providers:
        sonata_user_bundle:
            id: sonata.user.security.user_provider

    access_control:
      # Public Access to Soap Connector Urls
      - { path: ^/ws/soap,    role: IS_AUTHENTICATED_ANONYMOUSLY }
      # Protected Access to Core WebServices Urls
      - { path: ^/ws/splash,  role: IS_AUTHENTICATED_ANONYMOUSLY }