################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Fos User Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
# 172.111.0.100         toolkit.mailjet.local
#
################################################################################


version: '2'

services:

    ################################################################################
    # Application Container
    app:
        image: 'registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0'
        container_name:     dev.fos-user.local
        volumes:
            - symfony-var:/var/www/html/var
            - './:/var/www/html:ro'
        hostname:           dev.fos-user.local
        command:            /var/www/html/docker/app/docker-entrypoint.sh
        networks:
            fos-user:       { ipv4_address: 172.121.0.10, aliases: [ dev.fos-user.local ] }
            splashsync:     { aliases: [ dev.fos-user.local ] }

    ################################################################################
    # Splash Toolkit Container   
    toolkit:
        image: 'splashsync/toolkit'
        container_name:     toolkit.fos-user.local
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
        hostname:           toolkit.fos-user.local
        networks:
            fos-user:       { ipv4_address: 172.121.0.100, aliases: [ toolkit.fos-user.local ] }
            splashsync:     { aliases: [ toolkit.fos-user.local ] }

volumes:
    symfony-var: ~

networks:
    ################################################################################
    # Default Private Network    
    fos-user:
        driver: bridge
        ipam:
            config:
                - subnet: 172.121.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true