################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Fos User Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
# 172.121.0.10         app.symfony-user.local
# 172.121.0.100        toolkit.symfony-user.local
# 172.121.0.101        db.symfony-user.local
# 172.121.0.200        phpmyadmin.symfony-user.local
#
################################################################################

services:

    ################################################################################
    # Application Container
    app:
        build:
            context: ./docker/app
        container_name:     app.symfony-user.local
        volumes:
            - symfony-var:/var/www/html/var
            - './:/var/www/html'
        hostname:           app.symfony-user.local
        networks:
            symfony-user:   { ipv4_address: 172.121.0.10, aliases: [ app.symfony-user.local ] }
            splashsync:     { aliases: [ app.symfony-user.local ] }

    ################################################################################
    # MariaDb Container
    mariadb:
        image: mariadb:10
        container_name: db.symfony-user.local
        logging: { driver: "none" }
        environment:
            - "MYSQL_ROOT_PASSWORD=SPLASH_CI"
            - "MYSQL_DATABASE=SymfonyUsers"
        command: [ '--sql_mode=NO_ENGINE_SUBSTITUTION' ]
        hostname: mysql.splashsync.front
        networks:
            symfony-user:   { ipv4_address: 172.121.0.101, aliases: [ db.splashsync.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image:              'splashsync/toolkit:2.5'
        container_name:     toolkit.symfony-user.local
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
        hostname:           toolkit.symfony-user.local
        networks:
            symfony-user:   { ipv4_address: 172.121.0.100, aliases: [ toolkit.symfony-user.local ] }
            splashsync:     { aliases: [ toolkit.symfony-user.local ] }

    ################################################################################
    # PhpMyAdmin Container
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: phpmyadmin.symfony-user.local
        depends_on:
            - mariadb
        environment:
            - PMA_HOST=mariadb
            - MYSQL_USER=Splash
            - MYSQL_ROOT_PASSWORD=SPLASH_CI
            - MYSQL_PASSWORD=SPLASH_CI
        networks:
            symfony-user:        { ipv4_address: 172.121.0.200, aliases: [ phpmyadmin.symfony-user.local ] }

volumes:
    symfony-var: ~

networks:
    ################################################################################
    # Default Private Network    
    symfony-user:
        driver: bridge
        ipam:
            config:
                - subnet: 172.121.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true