################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Fos User Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
#    172.121.0.10       app.symfony-user.local
#    172.121.0.74    	sf7.symfony-user.local
#    172.121.0.64    	sf6.symfony-user.local
#    172.121.0.54    	sf5.symfony-user.local
#    172.121.0.44    	sf4.symfony-user.local
#    172.121.0.100    	toolkit.symfony-user.local
#
################################################################################

name: "splash-symfony-user"

services:

    ################################################################################
    # Application Container (Symfony 7.x - Current Version)
    app:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.4"
        container_name: app.symfony-user.local
        hostname:       app.symfony-user.local
        tty:            true
        volumes:
            - ./:/var/www/html
            - app-var:/var/www/html/var
            - app-vendor:/var/www/html/vendor
        environment:
            COMPOSER_ROOT_VERSION:  3.0.x-dev
            SERVER_ROOT:            /var/www/html/tests/public
        networks:
            default:        { ipv4_address: 172.121.0.10, aliases: [ app.symfony-user.local ] }

    ################################################################################
    # Symfony 7 + PHP 8.3
    sf7:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3"
        container_name: sf7.symfony-user.local
        hostname:       sf7.symfony-user.local
        tty:            true
        volumes:
            - ./:/var/www/html
            - sf7-var:/var/www/html/var
            - sf7-vendor:/var/www/html/vendor
        environment:
            SYMFONY_REQUIRE:        7.*
            COMPOSER_ROOT_VERSION:  3.0.x-dev
            SERVER_ROOT:            /var/www/html/tests/public
        networks:
            default:        { ipv4_address: 172.121.0.74, aliases: [ sf7.symfony-user.local ] }

    ################################################################################
    # Symfony 6 + PHP 8.2
    sf6:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2"
        container_name: sf6.symfony-user.local
        hostname:       sf6.symfony-user.local
        tty:            true
        volumes:
            - ./:/var/www/html
            - sf6-var:/var/www/html/var
            - sf6-vendor:/var/www/html/vendor
        environment:
            SYMFONY_REQUIRE:        6.4.*
            COMPOSER_ROOT_VERSION:  3.0.x-dev
            SERVER_ROOT:            /var/www/html/tests/public
        networks:
            default:        { ipv4_address: 172.121.0.64, aliases: [ sf6.symfony-user.local ] }

    ################################################################################
    # Symfony 5 + PHP 8.1
    sf5:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1"
        container_name: sf5.symfony-user.local
        hostname:       sf5.symfony-user.local
        tty:            true
        volumes:
            - ./:/var/www/html
            - sf5-var:/var/www/html/var
            - sf5-vendor:/var/www/html/vendor
        environment:
            SYMFONY_REQUIRE:        5.4.*
            COMPOSER_ROOT_VERSION:  3.0.x-dev
        networks:
            default:        { ipv4_address: 172.121.0.54, aliases: [ sf5.symfony-user.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image:              'splashsync/toolkit:3.0'
        container_name:     toolkit.symfony-user.local
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yaml:/app/config/packages/splash.yaml:ro'
        hostname:           toolkit.symfony-user.local
        networks:
            default:   { ipv4_address: 172.121.0.100, aliases: [ toolkit.symfony-user.local ] }
            splashsync:     { aliases: [ toolkit.symfony-user.local ] }

volumes:
    app-var:        ~
    app-vendor:     ~
    sf7-var:        ~
    sf7-vendor:     ~
    sf6-var:        ~
    sf6-vendor:     ~
    sf5-var:        ~
    sf5-vendor:     ~


networks:
    ################################################################################
    # Default Private Network    
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.121.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true