
services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ########################################################################
    # Symfony Users Standalone Object Service
    Splash\Connectors\SymfonyUser\Objects\ThirdParty:
        arguments:
            $userClass:     "%splash.symfony.user.class%"
        tags:
          # Register Faker Standalone Connector Objects
          - { name: "splash.standalone.object", type : "ThirdParty" }

    ########################################################################
    # SymfonyUser Users Events Listener
    Splash\Connectors\SymfonyUser\EventListener\:
        resource: '../../EventListener'