
services:
    _defaults:
        autowire: true

    ########################################################################
    # Symfony Users Standalone Object Service
    Splash\Connectors\SymfonyUser\Objects\ThirdParty:
        arguments:
            $userClass:     "%splash.symfony.user.class%"
        tags:
          # Register Faker Standalone Connector Objects
          - { name: "splash.standalone.object", type : "ThirdParty" }

    ########################################################################
    # SymfonyUser Users Events EventSubscriber
    Splash\Connectors\SymfonyUser\EventSubscriber\DoctrineEventsSubscriber:
        arguments:
            - "@splash.connectors.manager"
        tags:
            - { name: 'doctrine.event_subscriber', priority: -1 }