
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # Symfony User Default
        symfony-user:
            id:                 ThisIsSfUserWsId
            key:                ThisIsNotASecretKeyForSfUser
            name:               Serveur 1 (Symfony Users)
            host:               false
            connector:          soap
            config:
                Extended:           true
                WsIdentifier:       ThisIsSfUserWsId
                WsEncryptionKey:    ThisIsNotASecretKeyForSfUser
                WsHost:             http://app.symfony-user.local
                WsPath:             /ws/splash

